//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Sharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class HASLA
    {
        public int ID_HASLO { get; set; }
        public int ID_UZYTKOWNIK { get; set; }
        public byte[] HASLO { get; set; }
    
        public virtual UZYTKOWNIK UZYTKOWNIK { get; set; }
    }
}
