//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Sharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSIAZKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KSIAZKA()
        {
            this.ZBIOR = new HashSet<ZBIOR>();
        }
    
        public int ID_KSIAZKA { get; set; }
        public string TYTUL { get; set; }
        public string WYDAWNICTWO { get; set; }
        public Nullable<short> WYDANIE { get; set; }
        public Nullable<short> ROK_WYDANIA { get; set; }
        public string ISBN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZBIOR> ZBIOR { get; set; }
    }
}
