//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Sharing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookSharingEntities : DbContext
    {
        public BookSharingEntities()
            : base("name=BookSharingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HASLA> HASLA { get; set; }
        public virtual DbSet<KSIAZKA> KSIAZKA { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UZYTKOWNIK> UZYTKOWNIK { get; set; }
        public virtual DbSet<ZBIOR> ZBIOR { get; set; }
    }
}
