//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Sharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZYTKOWNIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UZYTKOWNIK()
        {
            this.HASLA = new HashSet<HASLA>();
            this.ZBIOR = new HashSet<ZBIOR>();
        }
    
        public int ID_UZYTKOWNIK { get; set; }
        public string LOGIN { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HASLA> HASLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZBIOR> ZBIOR { get; set; }
    }
}
